apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: todoapp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todoapp-dep
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes:
        - name: picsum-image
          persistentVolumeClaim:
            claimName: todoapp-pvc
      containers:
        - name: todoapp
          image: todoapp
          volumeMounts:
            - name: picsum-image
              mountPath: /usr/src/app/files
          env:
          - name: PORT
            value: "4000"
          - name: STATIC_PATH
            value: "/usr/src/app/files/static"
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"