apiVersion: v1
kind: Secret
metadata:
  namespace: project
  name: db-url
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9wb3N0Z3Jlcz9zc2xtb2RlPWRpc2FibGU=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: todo-backend
          env:
          - name: PORT
            value: "4000"
          - name: NATS_URL
            valueFrom:
              configMapKeyRef:
                name: broadcaster-config
                key: NATS_URL
          - name: NATS_SUBJECT
            valueFrom:
              configMapKeyRef:
                name: broadcaster-config
                key: NATS_SUBJECT
          - name: STREAM_NAME
            valueFrom:
              configMapKeyRef:
                name: broadcaster-config
                key: STREAM_NAME
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-url
                key: DATABASE_URL
          readinessProbe:
            httpGet:
              path: /readiness
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /liveness
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 15 
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"