apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-app.yaml
  - deployment-backend.yaml
  - deployment-broadcaster.yaml
  - service-app.yaml
  - service-backend.yaml
  - ingress.yaml
  - psql-stateful.yaml
  - reminder-cron.yaml

images:
  - name: todoapp
    newName: europe-north1-docker.pkg.dev/YOUR_PROJECT_ID/my-repo/todo-app
    newTag: latest
  - name: todo-backend
    newName: europe-north1-docker.pkg.dev/YOUR_PROJECT_ID/my-repo/todo-backend
    newTag: latest
  - name: broadcaster
    newName: europe-north1-docker.pkg.dev/YOUR_PROJECT_ID/my-repo/broadcaster
    newTag: latest
